color_list = [None, "蓝", "紫", "绿", "黄", "青", "紫", "灰", "橙"]

civ_dict = {
    "Armenians": "亚美尼亚",
    "Aztecs": "阿兹特克",
    "Bengalis": "孟加拉",
    "Berbers": "柏柏尔",
    "Britons": "不列颠",
    "Bohemians": "波西米亚",
    "Bulgarians": "保加利亚",
    "Burgundians": "勃艮第人",
    "Burmese": "缅甸",
    "Byzantines": "拜占庭",
    "Celts": "凯尔特",
    "Chinese": "中国",
    "Cumans": "库曼",
    "Dravidians": "达罗毗荼",
    "Ethiopians": "埃塞俄比亚",
    "Franks": "法兰克",
    "Georgians": "格鲁吉亚",
    "Goths": "哥特",
    "Gurjaras": "瞿折罗",
    "Hindustanis": "印度斯坦",
    "Huns": "匈奴",
    "Incas": "印加",
    "Italians": "意大利",
    "Japanese": "日本",
    "Khmer": "高棉",
    "Koreans": "高丽",
    "Lithuanians": "立陶宛",
    "Magyars": "马扎尔",
    "Malay": "马来",
    "Malians": "马里",
    "Mayans": "玛雅",
    "Mongols": "蒙古",
    "Persians": "波斯",
    "Poles": "波兰",
    "Portuguese": "葡萄牙",
    "Romans": "罗马",
    "Saracens": "萨拉森",
    "Sicilians": "西西里",
    "Slavs": "斯拉夫",
    "Spanish": "西班牙",
    "Tatars": "鞑靼",
    "Teutons": "条顿",
    "Turks": "土耳其",
    "Vietnamese": "越南",
    "Vikings": "维京",
}


class NotFoundError(Exception):
    pass
